### PR TITLE
Added upsert method to move a specific item to the start.

### PR DESCRIPTION
**Pull request by PrimozPernat**
Created a solution as mentioned in https://github.com/stfalcon-studio/ChatKit/issues/201

### CODE REVIEW

**Comment by PrimozPernat** [comment]
@stfalcon @hbmartin @fre5h @philippeauriach Hello everyone. Can I bother one who has the write permission to go over the small PR and merge it? That would be appreciated.

**Comment by bevzaanton** [comment]
Hi @PrimozPernat ! Sorry that I did not reply for a while. PR looks very good. But why you made some fields and methods `public`? Maybe will be better if you make them `protected`. In this way users will have access to those fields and method by extending `MessagesListAdapter`. 
And if you have time, can you add new upsert method to the documentation?

**Comment by PrimozPernat** [comment]
@bevzaanton Thank you for the replay. I changed the access modifier for the `items` list and the method `generateDateHeaders` to `protected`. But the inner class `Wrapper<DATA>` has to be public because if someone wants to extend the `MessagesListAdapter` he can't access `item` in the list.

**Comment by bevzaanton** [comment]
@PrimozPernat thanks for PR! I will upload ChatKit version 0.3.3-SNAPSHOT with your changes.

**Pull request merged**
