### PR TITLE
Add typing listener

### PR DESCRIPTION
**Pull request by toanpv**
Add TypingListener to MessageInput for those who wants notify to his/her server about this event or to do something else...

### CODE REVIEW

**Comment by Xenero** [comment]
Any ETA on implementing this. It's a vital part of any chat app.

**Comment by Xenero** [comment]
I take it that active development on ChatKit has been suspended?

**Comment by mtangoo** [comment]
with 19 PR sitting with no response it seems that this useful project is slowly dying.
Am not sure if Forking and continuing it is a good way to go. I suggest @stfalcon  @bevzaanton finds a way to rescue this useful library!

**Comment by mario** [comment]
Hello,

considering that the library is not maintained and I actively use it, I have decided to fork it for the time being under the same name. Changes to naming and other practices will come in the future.

In the mean time, I will look at your PR and consider merging it.

I hope we can revive this project together.

https://github.com/mario/chatkit

Cheers,
Mario

**Comment by bevzaanton** [comment]
#40 merged

**Comment by fukemy** [comment]
@mario  404

**Pull request merged**
